name: Windows – Litemanager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building…
    runs-on: windows-latest

    steps:
      - name: Downloading & installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Connect to LiteManager
        run: |
          cmd /c show.bat
          # Check if LiteManager ID is displayed
          if ($LASTEXITCODE -ne 0) {
            Write-Host "Error running show.bat"
            exit 1
          }

      - name: Create Restore Point
        run: |
          powershell -Command "Checkpoint-Computer -Description 'Before LiteManager Setup' -RestorePointType 'MODIFY_SETTINGS'"

      - name: Time Counter
        run: |
          cmd /c loop.bat

      - name: Handle Cancellation
        if: ${{ github.event.action == 'workflow_run' }}
        run: |
          Write-Host "Workflow was canceled. Shutting down the system."
          shutdown /s /t 0
