name: Windows – Litemanager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building…
    runs-on: windows-latest

    steps:
      - name: Downloading & installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Connect to LiteManager
        run: |
          cmd /c show.bat
          # Check if LiteManager ID is available
          if not exist LiteManagerID.txt (
            echo "LiteManager ID not found. Exiting..."
            exit 1
          )

      - name: Time Counter
        run: cmd /c loop.bat

      - name: Handle Workflow Cancellation
        if: ${{ github.event.action == 'workflow_run' }}
        run: |
          echo "Workflow was canceled. Shutting down the system..."
          shutdown /s /t 0

      - name: Check Previous State
        run: |
          if exist previous_state.txt (
            echo "Resuming from previous state..."
            cmd /c resume.bat
          ) else (
            echo "No previous state found. Starting fresh..."
          )
