name: Windows – Litemanager

on:
  workflow_dispatch:

jobs:
  build:
    name: Start Building…
    runs-on: windows-latest

    steps:
      - name: Create Restore Point
        run: |
          powershell -Command "Checkpoint-Computer -Description 'Before Litemanager Workflow' -RestorePointType 'MODIFY_SETTINGS'"

      - name: Downloading & installing Essentials
        run: |
          Invoke-WebRequest -Uri "https://gitlab.com/chamod12/lm_win-10_github_rdp/-/raw/main/Downloads.bat" -OutFile "Downloads.bat"
          cmd /c Downloads.bat

      - name: Connect to LiteManager
        run: |
          cmd /c show.bat
          echo "LiteManager ID: 452507277"  # Replace with actual output if needed

      - name: Time Counter
        run: |
          cmd /c loop.bat
        continue-on-error: true  # Allow the job to continue even if this step fails

      - name: Handle Cancellation
        if: ${{ github.event.action == 'workflow_run' }}
        run: |
          echo "Workflow was canceled. Shutting down the system."
          shutdown /s /t 0
